dist: xenial
sudo: require
language: cpp
compiler:
    - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - freeglut3-dev
            - libjpeg-dev
            - libfreetype6-dev
            - libxrandr-dev
            - libglew-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - cmake

      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
    - sudo apt-get install libx11-dev freeglut3-dev libjpeg-dev libfreetype6-dev libxrandr-dev libglew-dev libsndfile1-dev libopenal-dev libudev-dev
    - mkdir sf
    - cd sf
    - git clone https://github.com/SFML/SFML.git
    - cd SFML
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D BUILD_SHARED_LIBS=TRUE .
    - make
    - sudo make install
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D BUILD_SHARED_LIBS=FALSE .
    - make
    - sudo make install
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=TRUE .
    - make
    - sudo make install
    - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=FALSE .
    - make
    - sudo make install
    - eval "${MATRIX_EVAL}"
script:
    - gcc -v && g++ -v && cmake --version
    - cd ..
    - cd ..
    - cmake CMakeLists.txt
    - make
