version: 2
jobs:
  build:
    docker:
      - image:  circleci/debian:stretch

    steps:
      - checkout  # check out src code into working directory

      - run:
          name: Set up
          command: |
            sudo apt-get update
            git submodule sync; git submodule update --init # initialize git submodules
            sudo apt-get install libsfml-dev                # version 2.4.2
            sudo apt-get install libyaml-cpp-dev            # version 0.5.2-4
            sudo apt-get install cmake
      - run:
          name: Compile
          command: cmake CMakeLists.txt
      - run:
          name: Make
          command: make
