version: 2
jobs:
  build:
    docker:
      - image:  "debian:stretch"

    steps:
      - checkout  # check out src code into working directory

      - run:
          name: Set up
          command: |
            apt-get update
            apt-get install git
            git submodule sync; git submodule update --init # initialize git submodules
            apt-get install libsfml-dev                # version 2.4.2
            apt-get install libyaml-cpp-dev            # version 0.5.2-4
            apt-get install cmake
      - run:
          name: Compile
          command: cmake CMakeLists.txt
      - run:
          name: Make
          command: make
